name: sociohydro
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - fenics
  - matplotlib
  - h5py
  - opencv
  - pip
  - pip:
    - dolfin-adjoint==2019.1.0
    - jupyterlab
    - pygmsh
    - tqdm
